cd C:\Projekte\AOC23
call ng g c day1
call ng g c day2
call ng g c day3
call ng g c day4
call ng g c day5
call ng g c day6
call ng g c day7
call ng g c day8
call ng g c day9
call ng g c day10
call ng g c day11
call ng g c day12
call ng g c day13
call ng g c day14
call ng g c day15
call ng g c day16
call ng g c day17
call ng g c day18
call ng g c day19
call ng g c day20
call ng g c day21
call ng g c day22
call ng g c day23
call ng g c day24
